# -*- coding: utf-8 -*-
"""CK_PCA_CUDA-v-aug25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vyiUpovPPosC2bEyMVMjhLfSe0BoRpVb
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd
from typing import Union
from tqdm import tqdm

gpu_info = !nvidia-smi
gpu_info = '\n'.join(gpu_info)
if gpu_info.find('failed') >= 0:
  print('Not connected to a GPU')
else:
  print(gpu_info)

import os
os.chdir('/content/drive/MyDrive/Colab Notebooks/')
print(os.getcwd())

"""# Helper Functions"""



"""# CK-PCA-CUDA"""

!pip install nvidia-ml-py3

import nvidia_smi

nvidia_smi.nvmlInit()

handle = nvidia_smi.nvmlDeviceGetHandleByIndex(0)
# card id 0 hardcoded here, there is also a call to get all available card ids, so we could iterate

def get_gpu_info():
    info = nvidia_smi.nvmlDeviceGetMemoryInfo(handle)
    return info

info = get_gpu_info()
print("Total memory:", info.total)
print("Free memory:", info.free)
print("Used memory:", info.used)

#info.total / (1024**3)
#nvidia_smi.nvmlShutdown()

import cupy as cp
import gc
import numpy as np
import pandas as pd
from typing import Union
from tqdm import tqdm
import nvidia_smi
from concurrent.futures import ThreadPoolExecutor, as_completed

nvidia_smi.nvmlInit()
handle = nvidia_smi.nvmlDeviceGetHandleByIndex(0)
# card id 0 hardcoded here, there is also a call to get all available card ids, so we could iterate

def get_gpu_info():
    info = nvidia_smi.nvmlDeviceGetMemoryInfo(handle)
    return info

# Enable memory pool
#cp.cuda.set_allocator(cp.cuda.MemoryPool().malloc)
mempool = cp.cuda.MemoryAsyncPool()
with cp.cuda.Device(0):
    #100 * (1024**2)
    #mempool.set_limit(size=1024**3) # 1 GiB
    info = get_gpu_info()
    gpu_limit = info.total - (200 * (1024**2)) # spare 200MB
    mempool.set_limit(size=gpu_limit)
cp.cuda.set_allocator(mempool.malloc)

def split_list(lst, n):
    k, m = divmod(len(lst), n)
    return [lst[i * k + min(i, m):(i + 1) * k + min(i + 1, m)] for i in range(n)]


class CKPCA(object):
    def __init__(self, kernel, c, characteristics_model, data_source, storage, freq, path_cache, batch_size=100,
                 devices=[0]):

        self.kernel = kernel
        self.c = c
        self.characteristics_model = characteristics_model
        self.data_source = data_source
        self.storage = storage
        self.freq = freq
        self.path_cache = path_cache
        self.batch_size = batch_size
        self.devices = devices

    @staticmethod
    def compute_linear_kernel(X1_device, X2_device):
        return cp.dot(X1_device, X2_device.T)

    @staticmethod
    def compute_polynomial_kernel(X1_device, X2_device, degree, coef0):
        linear_kernel = cp.dot(X1_device, X2_device.T)
        return (linear_kernel + coef0) ** degree

    @staticmethod
    def compute_rbf_kernel(X1_device, X2_device, length_scale):
        """Compute the RBF kernel."""
        X1_sq_norms = cp.sum(X1_device ** 2, axis=1).reshape(-1, 1)
        X2_sq_norms = cp.sum(X2_device ** 2, axis=1).reshape(1, -1)
        sq_dists = X1_sq_norms + X2_sq_norms - 2 * cp.dot(X1_device, X2_device.T)
        K_device = cp.exp(-sq_dists / (2 * length_scale ** 2))
        return K_device

    @staticmethod
    def calculate_centered_kernel_cuda(X1_device, X2_device, kernel_type: str, c: float, stream) -> np.ndarray:
        with stream:
            if kernel_type == 'linear':
                K_device = CKPCA.compute_linear_kernel(X1_device, X2_device)
            elif kernel_type == 'poly2':
                K_device = CKPCA.compute_polynomial_kernel(X1_device, X2_device, degree=2, coef0=c)
            elif kernel_type == 'rbf':
                K_device = CKPCA.compute_rbf_kernel(X1_device, X2_device, length_scale=c)
            else:
                raise ValueError(f"Unsupported kernel type: {kernel_type}")

            row_means = cp.mean(K_device, axis=1, keepdims=True)
            col_means = cp.mean(K_device, axis=0, keepdims=True)
            all_mean = cp.mean(K_device)
            centered_K_device = K_device - row_means - col_means + all_mean

        return centered_K_device

    def compute_omega_element_for_date_combination_cuda(
        self,
        characteristics_device: dict,
        asset_rets_device: dict,
        date1: str,
        date2: str,
        kernel_type: str = 'linear',
        c: float = 1,
    ) -> Union[float, pd.Series]:

        stream = cp.cuda.Stream(non_blocking=True)  # Create a non-blocking stream

        X1_device = characteristics_device[date1]
        X2_device = characteristics_device[date2]
        centered_K_device = CKPCA.calculate_centered_kernel_cuda(X1_device, X2_device, kernel_type=kernel_type, c=c, stream=stream)

        r1_device = asset_rets_device[date1]
        r2_device = asset_rets_device[date2]

        with stream:
            omega_device = cp.dot(cp.dot(r1_device, centered_K_device), r2_device)
            result = cp.asnumpy(omega_device)

        stream.synchronize()  # Synchronize the stream to ensure all operations are completed
        return result

    def process_on_device(self, device, date_combinations, characteristics, asset_rets):
        with cp.cuda.Device(device):
            #cp.cuda.Device(device).use()  # Set the current device

            omega_elements = []
            data_cache = {}
            ref_counts = {}

            # Precompute reference counts for dates
            for date1, date2 in date_combinations:
                for date in (date1, date2):
                    if date not in ref_counts:
                        ref_counts[date] = 0
                    ref_counts[date] += 1

            # Stream for overlapping data transfers
            transfer_stream = cp.cuda.Stream(non_blocking=True)

            hide_progress = True if device > 0 else False
            for batch_start in tqdm(range(0, len(date_combinations), self.batch_size),
                                    desc=f"Processing batches for device {device}", disable=hide_progress):
                batch_combinations = date_combinations[batch_start:batch_start + self.batch_size]
                dates_in_batch = list(set([date for date_pair in batch_combinations for date in date_pair]))

                # Preload data asynchronously
                new_data_to_load = [date for date in dates_in_batch if date not in data_cache]
                characteristics_device, asset_rets_device = {}, {}
                with transfer_stream:
                    characteristics_device, asset_rets_device = self.load_data_to_gpu(characteristics, asset_rets,
                                                                                      new_data_to_load)

                cp.cuda.Stream.synchronize(transfer_stream)  # Ensure all data is loaded before computation

                # Add newly loaded data to the cache
                for date in new_data_to_load:
                    data_cache[date] = {
                        'characteristics': characteristics_device[date],
                        'asset_rets': asset_rets_device[date],
                    }

                streams = [cp.cuda.Stream(non_blocking=True) for _ in range(len(batch_combinations))]
                results = []

                for stream, (date1, date2) in zip(streams, batch_combinations):
                    result = self.compute_omega_element_for_date_combination_cuda(
                        {date1: data_cache[date1]['characteristics'], date2: data_cache[date2]['characteristics']},
                        {date1: data_cache[date1]['asset_rets'], date2: data_cache[date2]['asset_rets']},
                        date1,
                        date2,
                        kernel_type=self.kernel,
                        c=self.c
                    )
                    results.append(result)

                    # Decrease reference counts and free memory if no longer needed
                    for date in (date1, date2):
                        ref_counts[date] -= 1
                        if ref_counts[date] == 0:
                            del data_cache[date]  # Unload data when no longer needed

                for stream in streams:
                    stream.synchronize()

                for result in results:
                    omega = float(result)
                    omega_elements.append(omega)

                # Synchronize to ensure all operations are complete before next batch
                cp.cuda.Device(device).synchronize()

                # Clean up memory
                del results
                del streams
                mempool.free_all_blocks()
                gc.collect()

        return zip(date_combinations, omega_elements)

    def process_date_combinations_cuda(
        self,
        characteristics: pd.DataFrame,
        asset_rets: pd.Series,
        date_combinations: list,
    ) -> zip:
        omega_elements_combined = []

        # Split date combinations across GPUs
        date_combinations_splits = split_list(date_combinations, len(self.devices))

        # Process each batch on respective GPUs
        with ThreadPoolExecutor(max_workers=len(self.devices)) as executor:
            futures = [
                executor.submit(self.process_on_device, device, date_combinations_splits[device], characteristics,
                                asset_rets)
                for device in self.devices
            ]
            for future in as_completed(futures):
                result = list(future.result())
                omega_elements_combined.extend(result)

        return omega_elements_combined

    def load_data_to_gpu(self, characteristics, asset_rets, dates):
        characteristics_device = {}
        asset_rets_device = {}
        for date in dates:
            characteristics_device[date] = cp.asarray(characteristics.xs(date, level=1).to_numpy(), dtype=cp.float64)
            asset_rets_device[date] = cp.asarray(asset_rets.xs(date, level=1).to_numpy(dtype=cp.float64))
        return characteristics_device, asset_rets_device


    def compute_omega(self,
        characteristics: pd.DataFrame,
        asset_rets: pd.Series
    ):
        """Main function of the class. It computes the omega matrix for CK-PCA."""

        # Get the unique dates in the sample
        sample_dates = asset_rets.index.get_level_values(1).unique().sort_values()

        # Initialize omega as a DataFrame
        self.omega = pd.DataFrame(index=sample_dates, columns=sample_dates)

        # Create unique date combinations where d1 <= d2
        date_combinations = [(d1, d2) for i, d1 in enumerate(sample_dates) for d2 in sample_dates[i:]]

        # Parallel computation of omega
        omega_elements = self.process_date_combinations_cuda(characteristics, asset_rets, date_combinations)

        # Populate the omega DataFrame with the chunk results
        for (date1, date2), value in omega_elements:
            self.omega.loc[date1, date2] = value
            self.omega.loc[date2, date1] = value

        self.omega = self.omega.astype(np.float64)

        # Cache omega to pickle file
        self.omega.to_parquet(
            f"{self.path_cache}/{self.omega_name}.parquet",
            engine="pyarrow"
        )

        self.fit = True

    def fit(self, characteristics: pd.DataFrame, asset_rets: pd.Series):
        """The fit method for the CK-PCA class serves as the main entry point for the class.

        It initializes class parameters and checks if omega is already pre-computed and cached.
        If omega is not pre-computed, it calls the function to compute omega.

        Args:
            characteristics (pd.DataFrame): A DataFrame of characteristics data.
            asset_rets (pd.Series): A Series of asset returns data.
        """

        # Set the sample dates based on the asset returns
        self.set_sample_dates(asset_rets)

        # Initializes omega name and checks if omega is already pre-computed
        self.init_omega()

        if not self.fit:
            print('Fitting CK-PCA...')
            self.compute_omega(characteristics, asset_rets)

        print('CK-PCA fit complete.')

    def set_sample_dates(self, asset_rets: pd.Series):
        """This function sets two class parameters based on the asset returns data.

        Ultimate sample start (end) date are important, as they define the name of
        the cached omega matrices.

        Args:
            asset_rets (pd.Series): Sample asset returns data.
        """
        sample_dates = asset_rets.index.get_level_values(1).unique().sort_values()
        self.ultimate_sample_start_date = sample_dates[0].strftime('%Y-%m-%d')
        self.ultimate_sample_end_date = sample_dates[-1].strftime('%Y-%m-%d')

    def init_omega(self):
        """Initializes the omega attribute based on the parameters provided.

        This method constructs the omega name string based on the kernel type and other parameters.
        If the kernel is 'linear', the omega name is constructed without the 'c' parameter.
        Otherwise, the 'c' parameter is included in the omega name.
        After constructing the omega name, it attempts to load the pre-calculated omega from the cache.

        Parameters:
        None

        Returns:
        None
        """

        if self.kernel == 'linear':
            self.omega_name = (
                f"omega_{self.kernel}_"
                f"{self.ultimate_sample_start_date}_"
                f"{self.ultimate_sample_end_date}_"
                f"{self.characteristics_model}_"
                f"{self.data_source}_"
                f"{self.freq}"
            )
        else:
            self.omega_name = (
                f"omega_{self.kernel}_"
                f"{self.c}_"
                f"{self.ultimate_sample_start_date}_"
                f"{self.ultimate_sample_end_date}_"
                f"{self.characteristics_model}_"
                f"{self.data_source}_"
                f"{self.freq}"
            )

        # Attempt to load the pre-calculated omega
        self.load_omega_from_cache()

    def load_omega_from_cache(self):
        """Attempts to load omega from the cache based on the storage type.
        """
        if self.storage == 'local':
            self.load_omega_from_cache_local()
        elif self.storage == 'cloud':
            raise NotImplementedError('Cloud storage not implemented yet.')

    def load_omega_from_cache_local(self):
        """Checks if the omega is already pre-computed and cached.

        If it is, it loads the omega from the cache and sets fit attribute to True. Otherwise,
        it sets the fit attribute to False.
        """
        try:
            # Attempt to load omega from a pickle file
            self.omega = pd.read_pickle(f"{self.path_cache}/{self.omega_name}.p")
            self.fit = True
        except FileNotFoundError:
            try:
                # If pickle file is not found, attempt to load from a CSV file
                self.omega = pd.read_parquet(f"{self.path_cache}/{self.omega_name}.parquet")
                self.fit = True
            except FileNotFoundError:
                # If neither file is found, set fit to False
                self.fit = False

    def transform(self, split_date: str):
        """Calls functions to compute CK-PCs for IS and OOS period, based on the provided split date.

        Contrary to typical sklearn transform methods, this method does not take any input data. This
        is due to the fact that once the class is fitted, only omega is required to compute CK-PCs.

        Args:
            split_date (str): The date used to split the data into in-sample and out-of-sample sets.

        Returns:
            tuple: A tuple containing two DataFrames:
                - ck_pcs_is (pd.DataFrame): The principal components for the in-sample data.
                - ck_pcs_oos (pd.DataFrame): The principal components for the out-of-sample data.
        """

        ck_pcs_is = self.get_ck_pcs_is(split_date)

        ck_pcs_oos = self.get_ck_pcs_oos(split_date)

        return ck_pcs_is, ck_pcs_oos


    def get_ck_pcs_is(self, split_date: str):
        """Computes the CK-PCs for the in-sample period based on the provided split date.

        This function filters the omega matrix to only include dates before the split date. It then
        computes the eigenvectors of the filtered omega matrix and returns the scaled eigenvectors as
        the CK-PCs for the in-sample period.

        Args:
            split_date (str): The date used to split the data into in-sample and out-of-sample sets.

        Raises:
            ValueError: If the eigenvectors are empty, an error is raised.

        Returns:
            pd.DataFrame: The CK-PCs for the in-sample period.
        """

        # filter omega to only include dates before the split date
        is_row_indices = self.omega.index.get_level_values(0) <= split_date
        is_col_indices = self.omega.index.get_level_values(0) <= split_date
        omega_is = self.omega.loc[is_row_indices, is_col_indices]

        # CK-PCA: Scaled eigenvectors of omega correspond to CK-PCs
        _, ck_pcs_is = CKPCA.get_eigenvalues_eigenvectors(omega_is, rescale=True, plot=False)

        # if self.eigenvectors is empty, throw an error
        if ck_pcs_is.empty:
            raise ValueError('Failed to compute eigenvectors and eigenvalues.')

        return ck_pcs_is


    def get_ck_pcs_oos(self, split_date: str):
        """_summary_

        Args:
            split_date (str): The date used to split the data into in-sample and out-of-sample sets.

        Returns:
            pd.DataFrame: The CK-PCs for the out-of-sample period.
        """

        # filter omega to only include dates before the split date
        is_row_indices = self.omega.index.get_level_values(0) <= split_date
        is_col_indices = self.omega.index.get_level_values(0) <= split_date
        omega_is = self.omega.loc[is_row_indices, is_col_indices]

        # CK-PCA: Eigenvectors and lamba are used to weight the out-of-sample data
        lambdas, alphas = CKPCA.get_eigenvalues_eigenvectors(omega_is, rescale=True, plot=False)

        # filter omega to only include cols after the split date
        oos_col_indices = self.omega.index.get_level_values(0) > split_date
        omega_oos = self.omega.loc[is_row_indices, oos_col_indices]

        # compute CK-PCs for the out-of-sample period
        ck_pcs_oos = lambdas[0]**(-1)*((alphas.T @ omega_oos).T)

        return ck_pcs_oos


    @staticmethod
    def get_eigenvalues_eigenvectors(
        omega: pd.DataFrame,
        rescale: bool = True,
        plot: bool = False
    ) -> tuple[pd.DataFrame, pd.DataFrame]:
        """Computes the eigenvalues and eigenvectors of the given omega matrix.

        This method calculates the eigenvalues and eigenvectors of the omega matrix,
        sorts the eigenvalues in descending order, and adjusts the eigenvectors accordingly.
        Optionally, it can plot the eigenvalues and rescale the eigenvectors.

        Args:
            omega (pd.DataFrame): The omega matrix for which to compute eigenvalues and eigenvectors.
            rescale (bool): Whether to rescale the eigenvectors by the square root of the eigenvalues.
            plot (bool): Whether to plot the eigenvalues.

        Returns:
            tuple[pd.DataFrame, pd.DataFrame]: A tuple containing:
                - eigenvalues (pd.DataFrame): The sorted eigenvalues.
                - eigenvectors (pd.DataFrame): The corresponding eigenvectors.
        """

        # Perform eigenvalue decomposition on omega
        eigenvalues, eigenvectors = np.linalg.eigh(omega)

        # Convert eigenvectors and eigenvalues to DataFrames
        eigenvectors = pd.DataFrame(eigenvectors)
        eigenvalues = pd.DataFrame(eigenvalues)

        eigenvalues = eigenvalues.sort_values(by=0, ascending=False)

        # Reverse the order of the columns in eigenvectors
        eigenvectors = (
            eigenvectors
            .iloc[:, ::-1]
            .iloc[:, :eigenvalues[eigenvalues[0] > 0].shape[0]]
        )

        # Rename columns of eigenvectors to PC1, PC2, ...
        eigenvectors.columns = [f'PC{i+1}' for i in range(eigenvectors.shape[1])]
        eigenvectors.index = omega.index
        eigenvalues.index = [f'PC{i+1}' for i in range(eigenvalues.shape[0])]

        eigenvalues = eigenvalues[eigenvalues[0] > 0]

        if plot:
            eigenvalues.plot()

        if rescale:
            eigenvectors = eigenvectors * np.sqrt(eigenvalues[0])

        return eigenvalues, eigenvectors

"""# Load and run CK-PCA"""

# OSAP
parameters = {
    'data_source': 'OSAP',
    'c': np.nan,
    'ultimate_sample_start_date': '1973-11-01',
    'sample_start_date': '1973-11-01',
    'oos_split_date': '2024-12-31',
    'sample_end_date': '2024-12-31',
    'ultimate_sample_end_date': '2024-12-31',
    'freq_rets': 'M',
    'characteristics_model': 'cz46',
    'path_cache': 'omega_cached',
    'export_results': True,
}

parquet_path = "Data/cached_data/osap_characteristics_with_fwd_1m_rets_20260109.parquet"
characteristics = pd.read_parquet(parquet_path, engine="pyarrow")

fwd_rets_1m = characteristics['re'].copy()
characteristics = characteristics.drop(columns=['re', 'retadj'])
characteristics



if parameters['characteristics_model'] == 'cz45':
  model_factors = [
                # Original
                "Beta",              # CAPM beta
                "Size",              # Size
                "OperProf",          # Operating profits / book equity
                "BMdec",             # Book to market using December ME
                "AssetGrowth",       # Asset growth
                "Mom6m",             # Momentum (6 month)
                "STreversal",        # Short term reversal
                "IndMom",            # Industry Momentum
                "Illiquidity",       # Amihud's illiquidity
                "Leverage",          # Market leverage
                "MomSeasonShort",    # Return seasonality last year
                #"sgr",               # Revenue Growth Rank (assumed for "sgr")
                "InvGrowth",
                "EarningsSurprise",
                "Accruals",          # Accruals
                #"DivYieldAnn",       # Dividend Yield Annual (custom)
                "IdioVol3F",         # Idiosyncratic risk (3 factor)

                # 23 additional, previously added
                "EP",                # Earnings-to-Price Ratio
                "SP",                # Sales-to-price
                "ChInvIA",           # Change in capital investment (industry adjusted)
                "grcapx",            # Change in CapEx (two years)
                "ChInv",             # Inventory Growth
                "NOA",               # Net Operating Assets
                "CBOperProf",        # Cash-based Operating Profitability
                "GP",                # Gross profits / total assets
                "roaq",              # Return on assets (quarterly)
                "RoE",               # Net income / book equity
                "Tax",               # Taxable income to income
                "Mom12m",            # Momentum (12 month)
                "MomSeason",         # Return seasonality years 2 to 5
                "ReturnSkew",        # Return skewness
                "BetaTailRisk",      # Tail risk beta
                "Coskewness",        # Coskewness
                "BidAskSpread",      # Bid-ask spread
                "zerotrade6M",       # Days with zero trades
                "NetEquityFinance",  # Net equity financing
                "ResidualMomentum",  # Residual momentum
                "PriceDelayRsq",     # Price delay R-squared
                "RDS",               # Realized downside skewness

                # 7 high-profile additions for robustness
                "CompEquIss",        # Composite equity issuance
                "Investment",        # Investment to revenue
                "cfp",               # Operating Cash Flows to price
                "MRreversal",        # Medium-run reversal
                "EquityDuration",    # Equity Duration
                "TotalAccruals",     # Total accruals
                "MaxRet",            # Maximum return over month
            ]

elif parameters["characteristics_model"] == "cz46":
  model_factors = [
    "Size", "BMdec", "Mom12m", "Mom6m", "STreversal", "GP", "AssetGrowth",
    "Accruals", "EP", "Beta", "IdioVol3F", "Illiquidity", "Leverage",
    "ShareIss1Y", "LRreversal", "roaq", "NOA", "CF", "IndMom", "IntMom",
    "ResidualMomentum", "SP", "EntMult", "CBOperProf", "Investment",
    "InvestPPEInv", "hire", "CompEquIss", "XFIN", "MaxRet", "OPLeverage",
    "BookLeverage", "Price", "EarningsSurprise", "TrendFactor", "grcapx",
    "MRreversal", "Cash", "BetaTailRisk", "Herf", "High52", "MomSeasonShort",
    "Tax", "VolSD", "VarCF", "CoskewACX",
]
elif parameters['characteristics_model'] == 'cz60':
  model_factors = [
      "Size",
      "BM", "EP", "cfp", "SP", "AM", "NetPayoutYield",
      "GP", "CBOperProf", "CashProd", "roaq",
      "AssetGrowth", "Investment", "ChEQ", "dNoa", "DelLTI", "DelEqu",
      "ChInv", "ChNWC", "DelCOA", "ChInvIA", "grcapx3y", "TotalAccruals",
      "Accruals", "AbnormalAccruals", "PctAcc",
      "Cash", "NOA", "VarCF",
      "ShareIss1Y", "XFIN", "NetDebtFinance", "NetEquityFinance",
      "BookLeverage", "Leverage",
      "Mom12m", "Mom6m", "IntMom", "IndMom",
      "STreversal", "LRreversal",
      "ChAssetTurnover", "RevenueSurprise", "EarningsSurprise",
      "Illiquidity", "BidAskSpread", "DolVol", "VolSD", "zerotrade12M", "ShortInterest", "BetaLiquidityPS",
      "RealizedVol", "IdioVol3F", "Beta", "Coskewness", "ReturnSkew",
      "Price", "OPLeverage", "FirmAge", "BetaFP",
  ]
elif parameters['characteristics_model'] == 'cz82':
  model_factors = ['Accruals',
 'AssetGrowth',
 'Beta',
 'BetaFP',
 'BetaTailRisk',
 'BidAskSpread',
 'BMdec',
 'BookLeverage',
 'Cash',
 'CashProd',
 'CBOperProf',
 'CF',
 'cfp',
 'ChEQ',
 'ChInv',
 'ChInvIA',
 'CompEquIss',
 'CompositeDebtIssuance',
 'Coskewness',
 'DelCOA',
 'DelCOL',
 'DelFINL',
 'DelLTI',
 'DelNetFin',
 'EarningsSurprise',
 'EBM',
 'EntMult',
 'EP',
 'EquityDuration',
 'GP',
 'grcapx',
 'GrLTNOA',
 'GrSaleToGrInv',
 'Herf',
 'High52',
 'hire',
 'IdioVol3F',
 'Illiquidity',
 'IndMom',
 'IntMom',
 'Investment',
 'InvestPPEInv',
 'Leverage',
 'LRreversal',
 'MaxRet',
 'MeanRankRevGrowth',
 'Mom12m',
 'Mom12mOffSeason',
 'Mom6m',
 'MomOffSeason',
 'MomOffSeason06YrPlus',
 'MomSeason',
 'MomSeason06YrPlus',
 'MomSeasonShort',
 'MRreversal',
 'NetDebtFinance',
 'NetEquityFinance',
 'NOA',
 'OPLeverage',
 'PriceDelayRsq',
 'PriceDelaySlope',
 'PriceDelayTstat',
 'RDS',
 'ResidualMomentum',
 'ReturnSkew',
 'roaq',
 'RoE',
 'ShareIss1Y',
 'Size',
 'SP',
 'STreversal',
 'Tax',
 'TotalAccruals',
 'TrendFactor',
 'VarCF',
 'VolMkt',
 'VolSD',
 'VolumeTrend',
 'XFIN',
 'zerotrade6M',
 'InvGrowth',
 'OperProf']


elif parameters['characteristics_model'] == 'cz10':
  model_factors = [
    "Accruals", "BM", "IdioVol3F", "AssetGrowth", "Size",
    "LRreversal", "OperProf", "Mom12m", "STreversal", "LTurnover"
]


characteristics = characteristics[model_factors]
characteristics

characteristics = characteristics.loc[
    (characteristics.index.get_level_values('date') >= np.datetime64(parameters["sample_start_date"])) &
    (characteristics.index.get_level_values('date') <= np.datetime64(parameters["sample_end_date"]))
]



def drop_low_coverage_securities(characteristics, max_missing):
    """Filter out (permno, date) rows with too many missing characteristics.

    Args:
        characteristics (pd.DataFrame): Wide DataFrame indexed by (permno, date),
            columns are characteristics.
        max_missing (float): Maximum allowed fraction of missing values per row
            in [0, 1]. Example: 0.30 keeps rows with up to 30% missing (>=70% coverage)
            and drops rows with more than 30% missing.

    Returns:
        pd.DataFrame: Characteristics with rows exceeding the missingness threshold removed.
    """
    if not (0 <= max_missing <= 1):
        raise ValueError(f"max_missing must be in [0, 1], got {max_missing}")

    # Missing ratio across columns per row
    na_ratio = characteristics.isna().mean(axis=1)

    # Drop rows where missingness exceeds the threshold
    to_drop = na_ratio > max_missing
    n_total = len(to_drop)
    n_drop = int(to_drop.sum())
    pct_drop = (n_drop / n_total * 100) if n_total else 0.0
    print(
        "[missing-filter] Threshold: allow up to "
        f"{max_missing:.0%} missing (i.e., require ≥ {(1 - max_missing):.0%} coverage)."
    )
    print(
        f"[missing-filter] Dropping {n_drop} of {n_total} rows "
        f"({pct_drop:.2f}%) where missing > {max_missing:.0%}."
    )

    kept = characteristics[~to_drop].copy()
    return kept

characteristics = drop_low_coverage_securities(characteristics, max_missing=0.3)
characteristics



import pandas as pd
import numpy as np

def compute_characteristic_signals(characteristics: pd.DataFrame) -> pd.DataFrame:
    """
    Compute characteristic signals for every date in the given characteristics DataFrame, adjusted for leverage.

    Parameters:
    characteristics (pd.DataFrame): DataFrame containing characteristics with a MultiIndex (date, other levels).

    Returns:
    pd.DataFrame: DataFrame with computed characteristic signals for each date, adjusted for leverage.
    """
    def leverage_adjust(signal):
        leverage_factor = 1 / signal[signal > 0].sum()
        return signal * leverage_factor

    # Rank the characteristics
    characteristics_ranked = characteristics.groupby(level='date').rank(method='average') / (characteristics.groupby(level='date').transform('count') + 1)

    # Compute the mean of the ranked characteristics
    characteristics_mean = characteristics_ranked.groupby(level='date').transform('mean')

    # Compute the signal
    characteristics_signal = characteristics_ranked - characteristics_mean

    # Normalize the signal
    characteristics_signal = characteristics_signal.groupby(level='date').transform(lambda x: x / x.abs().mean())

    # Adjust for leverage
    characteristics_signal = characteristics_signal.groupby(level='date').transform(leverage_adjust)

    # divide all signals by 2
    characteristics_signal = characteristics_signal / 2

    return characteristics_signal


characteristics = compute_characteristic_signals(
    characteristics
)
characteristics





characteristics[characteristics > 0].iloc[:,:].groupby('date').sum().plot(backend='plotly')

characteristics

asset_rets = fwd_rets_1m.reindex(characteristics.index)
asset_rets

characteristics.fillna(0, inplace=True)
characteristics.head(3)



#parameters['characteristics_model'] = "ffc5"
if parameters['characteristics_model'] == 'ffc5':
  characteristics = characteristics[['Mom6m', 'BMdec', 'GP', 'InvestPPEInv', 'Size']]
characteristics.head(3)





"""## Run CK-PCA"""



ckpca = CKPCA(
    kernel='linear',
    c=np.nan,
    characteristics_model=parameters['characteristics_model'],
    data_source=parameters['data_source'],
    storage='local',
    path_cache=parameters['path_cache'],
    freq=parameters['freq_rets'],
    batch_size=300,
    devices=[0],
)

ckpca.fit(characteristics, asset_rets)

ck_pcs_is, ck_pcs_oos = ckpca.transform(split_date=parameters['oos_split_date'])

pcs_full_sample = pd.concat([ck_pcs_is, ck_pcs_oos], axis=0)

"""## fit c-grid"""



# Define the grid of kernel hyperparameters
c_grid = np.logspace(-4, 0, 20)

for c in c_grid:
    parameters['c'] = c
    ckpca = CKPCA(
        kernel="rbf",
        c=parameters['c'],
        characteristics_model=parameters['characteristics_model'],
        data_source=parameters['data_source'],
        storage='local',
        path_cache=parameters['path_cache'],
        freq=parameters['freq_rets'],
        batch_size=300,
        devices=[0], # [0,1,2,...]
    )

    ckpca.fit(characteristics, asset_rets)



# Define the grid of kernel hyperparameters
c_grid = np.logspace(-9, -1, 20)

for c in c_grid:
    parameters['c'] = c
    ckpca = CKPCA(
        kernel="poly2",
        c=parameters['c'],
        characteristics_model=parameters['characteristics_model'],
        data_source=parameters['data_source'],
        storage='local',
        path_cache=parameters['path_cache'],
        freq=parameters['freq_rets'],
        batch_size=300,
        devices=[0], # [0,1,2,...]
    )

    ckpca.fit(characteristics, asset_rets)





"""# Sanity check

## Poly2 Kernel
"""

# -----------------------------
# Cell 2 — Use YOUR transform_data
# -----------------------------
def transform_data(characteristics, c, include_constant=False):
    # Step 1: Original Features Squared
    squared_features = characteristics ** 2
    squared_features.columns = [f'{col}^2' for col in characteristics.columns]

    # Step 2: Pairwise Interaction Terms
    X = characteristics.values
    n_samples, n_features = X.shape
    col_names = characteristics.columns

    # Get upper triangle indices for combinations (i < j)
    idx_upper = np.triu_indices(n_features, k=1)
    # Compute interactions using numpy's advanced indexing and broadcasting
    interactions = np.sqrt(2) * X[:, idx_upper[0]] * X[:, idx_upper[1]]

    # Create column names for interaction terms
    interaction_col_names = [
        f'{col_names[i]}_{col_names[j]}' for i, j in zip(idx_upper[0], idx_upper[1])
    ]

    # Create DataFrame for interaction terms
    interaction_terms = pd.DataFrame(
        interactions, columns=interaction_col_names, index=characteristics.index
    )

    # Step 3: Include Original Features Scaled by sqrt(2c)
    linear_terms = np.sqrt(2 * c) * characteristics

    if include_constant:
        # Step 4: Add constant term
        constant_term = pd.DataFrame(
            c, index=characteristics.index, columns=['constant']
        )
        return pd.concat(
            [squared_features, interaction_terms, linear_terms, constant_term], axis=1
        )

    return pd.concat(
        [squared_features, interaction_terms, linear_terms], axis=1
    )


# -----------------------------
# Cell 3 — Expand the characteristic space (poly2) and show the df
# -----------------------------
c_sanity = c_grid[10]
transformed_df = transform_data(characteristics, c=c_sanity, include_constant=False)

print("Expanded characteristics (poly2) shape:", transformed_df.shape)
display(transformed_df.head())

# -----------------------------
# Cell 4 — Cross-sectionally de-mean expanded characteristics (portfolio weights)
# -----------------------------
transformed_df = transformed_df.groupby(level="date").transform(lambda x: x - x.mean())

# sanity check: cross-sectional mean ~ 0 per date (show a few dates)
chk = transformed_df.groupby(level="date").mean().abs().mean(axis=1).head(5)
display(chk.rename("avg_abs_cs_mean_per_date"))

# -----------------------------
# Cell 5 — Construct factor returns (managed portfolios)
# factor_t = sum_i (w_{i,t} * r_{i,t})
# -----------------------------
factor_rets = transformed_df.multiply(asset_rets, axis=0).groupby(level="date").sum()

print("Factor return matrix shape (T x F):", factor_rets.shape)
display(factor_rets.iloc[:5, :8])

factor_rets.add(1).cumprod().plot(backend="plotly")

# -----------------------------
# Cell 6 — Extract PCs via classic PCA (rotate_rets) on factor returns
# -----------------------------
def rotate_rets(rets, rets_is=None):
    anomalies = ['PC' + str(i) for i in range(1, len(rets.columns) + 1)]

    if rets_is is None:  # If no in-sample data is provided, use rets
        rets_is = rets

    _, _, Q = np.linalg.svd(np.cov(rets_is, rowvar=False))
    Q = pd.DataFrame(Q, columns=rets.columns, index=anomalies)

    re_rotated = rets @ Q.T
    return pd.DataFrame(re_rotated, index=rets.index, columns=anomalies)


pcs_explicit = rotate_rets(factor_rets)   # full-sample PCA
display(pcs_explicit.head())

# run CK-PCA(poly2) with the same c
ckpca_poly2 = CKPCA(
    kernel="poly2",
    c=float(c_sanity),
    characteristics_model=parameters["characteristics_model"],
    data_source=parameters["data_source"],
    storage="local",
    path_cache=parameters["path_cache"],
    freq=parameters["freq_rets"],
    dtype="float64",
)
ckpca_poly2.fit(characteristics, asset_rets)

split_date = parameters["oos_split_date"]
ck_pcs_is = ckpca_poly2.get_ck_pcs_is(split_date)

# align the explicit PCs to the same IS window
pcs_exp_is = pcs_explicit.loc[ck_pcs_is.index]

# compare first K PCs by correlation (allow sign flips)
K = 150
K = min(K, ck_pcs_is.shape[1], pcs_exp_is.shape[1])

rows = []
for i in range(K):
    a = ck_pcs_is.iloc[:, i].to_numpy()
    b = pcs_exp_is.iloc[:, i].to_numpy()
    corr = np.corrcoef(a, b)[0, 1]
    rows.append((f"PC{i+1}", corr, abs(corr)))

cmp = pd.DataFrame(rows, columns=["PC", "corr", "abs_corr"]).set_index("PC")
display(cmp)

fig = cmp["abs_corr"].plot(backend="plotly")
fig.update_yaxes(range=[0, 1.1])   # or [0, 1.05]
fig.show()

pcs_exp_is.var().iloc[:(K+5)].plot(backend="plotly")

import seaborn as sns
sns.heatmap(pcs_explicit.iloc[:,:K] - ck_pcs_is.iloc[:,:K].round(10))

ck_pcs_is

pcs_explicit







